### ISSUE TITLE
Extra scripts didn't work

### ISSUE THREAD

**Issue by Yur-ok** [builtbybel/burnbytes#13]
Hi!
I downloaded extra scripts and extract them into installation dir.
But after restarting **Privatezilla** button **Scripts** didn't appear.
What I'm did wrong?

**Comment by Belim** [comment]
Uhh its not Monday but the Privatezilla repo is here https://github.com/builtbybel/privatezilla
:satisfied:

but nevertheless the folder must be named `scripts`
